[package]
name = "two"
version = "0.1.0"
edition = "2021"
authors = ["umbrella"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

keywords = ["bmp", "image"]

[dependencies]
byteorder ="1.5.0"